title:            "Michelle Hertzfeld &#8211; Web and UX Designer"
description:      Michelle Hertzfeld is a web designer and user experience specialist. Making content and communications kinder and clearer since 2001.

lsi: false
highlighter: pygments

# Comment out url when working locally to resolve base urls correctly
#url:             http://meiqimichelle.github.io/mhertzfeld
url:              http://localhost:4000

logo:             /assets/img/apple-touch-icon-144x144-precomposed.png

# Owner/author information
owner:
  name:           Michelle Hertzfeld
  avatar:         /assets/img/michelle.jpg
  bio:            "Michelle Hertzfeld is a web designer and user experience specialist. Making content and communications kinder and clearer since 2001."
  email:          design@mhertzfeld.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        https://twitter.com/meiqimichelle
  facebook:       https://www.facebook.com/meiqimichelle
  github:         https://github.com/meiqimichelle
  linkedin:       http://www.linkedin.com/in/michellehertzfeld
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   https://plus.google.com/u/0/102306465635177918694/posts

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-44962228-1
google_verify:      hBW-jTfpErtq8HQGzA-lbJDXw940n2fEMwr-Gc_MLXc
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        6E4C7F711615E1F2F0B1A7AAFDA28B1A

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
markdown:    kramdown
markdown_ext:  markdown,mkd,mkdn,md
excerpt_separator: <!--more-->

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

# Amount of post to show on home page
paginate: 5
paginate_path: "/thoughts/page:num"

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "_site", "assets/.sass-cache/"]
